version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
  mysqldatabase:
    image: mysql:latest
    container_name: mysqldatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '2000m'

volumes:
  mysql-volume:
